//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSPCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionTableDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionTableDetail()
        {
            this.AnswerTableDetails = new HashSet<AnswerTableDetail>();
            this.QuestionTables = new HashSet<QuestionTable>();
        }
    
        public int QuestionTableDetailsID { get; set; }
        public string Q1 { get; set; }
        public string A1_1 { get; set; }
        public string A1_2 { get; set; }
        public string A1_3 { get; set; }
        public string A1_4 { get; set; }
        public string A1_5 { get; set; }
        public string Q2 { get; set; }
        public string A2_1 { get; set; }
        public string A2_2 { get; set; }
        public string A2_3 { get; set; }
        public string A2_4 { get; set; }
        public string A2_5 { get; set; }
        public string Q3 { get; set; }
        public string A3_1 { get; set; }
        public string A3_2 { get; set; }
        public string A3_3 { get; set; }
        public string A3_4 { get; set; }
        public string A3_5 { get; set; }
        public string A3_6 { get; set; }
        public string A3_7 { get; set; }
        public string Q4 { get; set; }
        public string A4_1 { get; set; }
        public string A4_2 { get; set; }
        public string A4_3 { get; set; }
        public string A4_4 { get; set; }
        public string Q5 { get; set; }
        public string A5_1 { get; set; }
        public string A5_2 { get; set; }
        public string A5_3 { get; set; }
        public string A5_4 { get; set; }
        public string Q6 { get; set; }
        public string A6_1 { get; set; }
        public string A6_2 { get; set; }
        public string A6_3 { get; set; }
        public string A6_4 { get; set; }
        public string A6_5 { get; set; }
        public string Q7 { get; set; }
        public string A7_1 { get; set; }
        public string A7_2 { get; set; }
        public string A7_3 { get; set; }
        public string A7_4 { get; set; }
        public string A7_5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerTableDetail> AnswerTableDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionTable> QuestionTables { get; set; }
    }
}
